services:
  node:
    container_name: web
    build:
      context: .
      dockerfile: node.dockerfile
    volumes:
      - ./certs:/var/www/node/certs
      - ./src:/var/www/node/src
      - ./web:/var/www/node/web
    restart: unless-stopped
    ports:
      - "3001:3001"
      - "8433:8433" #for hot module replacement
    tty: true